language: cpp
dist: bionic
env:
  global:
    - NAMEP=realty-$TRAVIS_BUILD_NUMBER-Linux.deb
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install -y gcc-7 g++-7 doxygen graphviz
- sudo apt-get install libopenblas-dev -y
- sudo apt-get install libdlib-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen doxygen.conf
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: "doc/html"
  on:
    branch: main
- provider: script
  skip_cleanup: true
  on:
    branch: main
  script:
  - curl -v -T $NAMEP -usacrartorium:$BINTRAY_API_KEY "https://api.bintray.com/content/sacrartorium/otus/12/$TRAVIS_BUILD_NUMBER/$NAMEP;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
